### ISSUE TITLE
[TASK]Verify already existing secrets encryption

### ISSUE THREAD

**Issue by kruc** [ondat/trousseau#10]
Check how custom encryption mechanism (kube api server flag --encryption-provider-config) will behave with already existing secrets

**Comment by rovandep** [comment]
This has been verified from a code and documentation perspective. 
See: https://github.com/ondat/trousseau/wiki/Trousseau-with-HashiCorp-Vault#replace-existing-kubernetes-secrets-with-encrypted-ones-using-trousseau-kubernetes-admins
