### ISSUE TITLE
[SUPPORT] Trying to deploy trousseau

### ISSUE THREAD

**Issue by nasirudheen** [ondat/trousseau#113]
Hi All,
I am trying to deploy trousseau with Hashicorp Vault as the backend for my Kubernetes cluster. I referred to this document,
https://github.com/ondat/trousseau/wiki/Trousseau-with-HashiCorp-Vault

Under the **Deploy trousseau daemonset section**  the daemonset manifest file  has a line under `spec.template.spec.containers.args`, 

`- --config-file-path=/opt/trousseau/config.yaml`

Is it required ? if so, what should be the content of `config.yaml` ? I could see some sample config.yaml file in the repo with Vault server address and the token in plain text. But this document is not saying anything about creating the file or the content of it. Please guide me on this or point to some docs.

Thanks in advance,
Nasir

**Comment by romdalf** [comment]
Hi Nasir, 
The /opt/trousseau will be created and the config.yaml file be generated and mounted for you from the ConfigMap when recovering the parameters from the Vault KV store.
Hoping that's helping. 
Rom

**Comment by romdalf** [comment]
@nasirudheen hopefully you succeeded to deploy Trousseau. 
The issue will be considered closed after 10 days of inactivity.

**Comment by nasirudheen** [comment]
Thanks indeed for your replies @romdalf. I was not able to test it yet. Will do that and update you here in a day or two. 
Sorry for the delay and thanks again !
Nasir

**Comment by romdalf** [comment]
> Thanks indeed for your replies @romdalf. I was not able to test it yet. Will do that and update you here in a day or two. Sorry for the delay and thanks again ! Nasir

Great! Do not hesitate to join us on Slack for less async discussions

**Comment by nasirudheen** [comment]
I have got it working without any issue. Here is the output from a etcdctl command to list a secret,
```
00000000  2f 72 65 67 69 73 74 72  79 2f 73 65 63 72 65 74  |/registry/secret|
00000010  73 2f 64 65 66 61 75 6c  74 2f 74 65 73 74 2d 73  |s/default/test-s|
00000020  65 63 72 65 74 0a 6b 38  73 3a 65 6e 63 3a 6b 6d  |ecret.k8s:enc:km|
00000030  73 3a 76 31 3a 76 61 75  6c 74 70 72 6f 76 69 64  |s:v1:vaultprovid|
00000040  65 72 3a 00 59 76 61 75  6c 74 3a 76 31 3a 56 73  |er:.Yvault:v1:Vs|
00000050  78 4c 4f 77 47 51 5a 63  72 41 79 66 30 66 4b 42  |xLOwGQZcrAyf0fKB|
00000060  79 35 73 53 6d 42 66 68  4d 66 39 33 35 37 72 6d  |y5sSmBfhMf9357rm|
00000070  5a 62 35 41 43 74 74 57  34 72 7a 4f 2f 47 33 6d  |Zb5ACttW4rzO/G3m|
00000080  4a 70 44 33 36 51 52 6b  59 6f 56 38 53 50 65 38  |JpD36QRkYoV8SPe8|
00000090  6c 43 55 53 57 43 51 74  38 74 6a 31 66 51 fd f1  |lCUSWCQt8tj1fQ..|
000000a0  9b 23 89 c2 95 36 8b 83  93 e7 41 ed 67 e0 8d 7e  |.#...6....A.g..~|
000000b0  e8 cf 16 21 87 fe 30 fa  30 9a cd 56 c5 a1 22 d0  |...!..0.0..V..".|
000000c0  49 78 fc 04 39 b7 8d dc  01 04 c9 f5 4a 23 1a bb  |Ix..9.......J#..|
000000d0  c7 ac dd 7d ec 50 c8 88  e1 93 66 14 af db 2f 41  |...}.P....f.../A|
000000e0  c5 5f 9f ae e3 e9 3c eb  ed f4 42 a2 5b b7 66 d1  |._....<...B.[.f.|
000000f0  65 61 20 d2 5f 00 9a 0a  ec 96 9f 33 e5 9a 63 76  |ea ._......3..cv|
00000100  1d 83 b8 8f 2c ec 4a 23  04 e7 d6 a1 4b e4 7e a0  |....,.J#....K.~.|
00000110  0b 0c c2 8a f7 ac 91 e4  44 97 f5 fe 5a 9a 41 c2  |........D...Z.A.|
00000120  13 89 e1 11 aa ba 18 33  f0 a7 df 77 5d 74 6b c4  |.......3...w]tk.|
00000130  b3 d5 ac 87 52 4e 7a d0  5e bc 23 f0 49 a1 74 94  |....RNz.^.#.I.t.|
00000140  92 ca 9a ef c4 bd f7 d7  b8 60 ee d4 90 ea 12 90  |.........`......|
00000150  72 f9 21 39 be 3d 1a ba  9f 15 64 5d 2d b9 c1 67  |r.!9.=....d]-..g|
00000160  fe 81 10 ba 81 56 8e bc  8b c4 a5 74 3d 60 1d 06  |.....V.....t=`..|
00000170  44 7d 0d fa 3d ce b8 bf  7f 05 24 32 bd 87 f1 34  |D}..=.....$2...4|
00000180  9d cb 61 35 74 21 80 76  dd 0b a7 e5 e8 16 22 89  |..a5t!.v......".|
00000190  de 3a 42 30 24 42 50 17  c3 73 ee 3b 8b 94 0a     |.:B0$BP..s.;...|
0000019f
```
Thank you so much for the great software and all your support |
P.S: I tried to join the slack channel, but it is insisting on having an ID on ondat, unfortunately. 

Regards,

**Comment by romdalf** [comment]
Thanks for the feedback ;)
From a Slack standpoint; you can join via this [link](https://join.slack.com/t/storageos/shared_invite/zt-1d13b275e-ysH2WbRPs3P0qosQ2zu1UQ) which is the hosted on the Ondat External User instance, then join the trousseau channel.

Closing the issue on this comment.
