### ISSUE TITLE
[USERSTORY] expand support to multiple KMS providers

### ISSUE THREAD

**Issue by rovandep** [ondat/trousseau#5]
Is it linked to a user story? (use the "#" to tag the user story)
#2 #3 #4

What do we want to build?
An universal KMS provider plugin for Kubernetes (see https://kubernetes.io/docs/tasks/administer-cluster/kms-provider/) for more details. 

Why do we want to build it?
To provide a Kubernetes native way to handle secrets, new and existing, without the need to deploy heavy components.

How do we want to design it?
- simple, light, and respectful of the Kubernetes KMS provider definition (see https://kubernetes.io/docs/tasks/administer-cluster/kms-provider/). 
- based on the encryption envelope scheme mechanism
- should be transparent for the users
- a first version would support Hashicorp Vault as KMS to store the key used for encryption/decryption 
- a first version would support self-hosted Kubernetes due to the need to restart the kube-apiserver with specific parameter "--encryption-provider-config"

**Comment by cannischan** [comment]
Review https://github.com/mozilla/sops to look at how to expand platform support

**Comment by cannischan** [comment]
- [ ] Draw architectural diagram @rovandep 
- [ ] Estimate effort for Google KMS - prioritised
- [ ] Estimate effort for AWS - next item

**Comment by rovandep** [comment]
This userstory has been subject to our design meeting for v2 on Thursday June 9th 2022 leading the following milestone: https://github.com/ondat/trousseau/milestone/2

See: #50 for up-to-date details
