### ISSUE TITLE
[EPIC] redesign KMS provider plugin

### ISSUE THREAD

**Issue by cannischan** [ondat/trousseau#50]
- [x] Run design session to determine how to redesign the plugin set up
- [ ] Write AC and requirements on this task

[Sequence diagram](https://sequencediagram.org/index.html#initialData=C4S2BsFMAIFkFdymgaVgZWgZ3gB1wPYBOwAUKQIYDGwx0AqlpEabhSSFSGwHbADmRAnmgBiXCB4BraACpZAYXDwswZvNbtQXXgKEjR4EPwAWeyJB5zFBPkPAAdK9FzgKPSBoBmt4BQDukFgEALaQAKxEkPyI7NBeAAxeAByoyViklgAmmhw67nrCuGJGpsAARsow8gAq+lhMFPAa5cI8WewAntDoBFRSkMDQA5C4zKRUvvbQdcINkE3Qk1GZfGDdaJggIa4AjKugwBsY0NuuAEyrOR1+5RRMYoKQnQBcu6gY+zcUdw+iT693ptLtlyIIimJzl5zpAAOzlaAKKIUNTYSBUKJDUT+ExgSCkRjMAC0AD4UOkXkiFqimBjBqRyVhSb1+oNhhYxkQXgBRHgYzq4IZRACOlCQ0AASoMiN1bPEKCBlCsWQMhiNOaTZipGvAlsRIDy+TLBdARaQtfNFstIKTNqcduBdob+SazXazo7bZ9ncahZBRZtdkSvegnbyXWRAyH7XsfQK-VhcAyTh6gySLTq9VE466gkmMwtddbg+n6pnrS8AApRLwgAAeMfA0COY0orQbRGMZmgBC8MzLhazBoLixAWGgFGwkn4UBcBEkwAANE5AtATBQAG4wWjDHgEfzNkzb9j8Nm4IQbkBZZhOXvQSBbmVoulkEdF-XMvqq9mjZg5hNJqCKpsuqxJkhS4a+qaeYMukpKEly5wJAk0AAPIoFcYL6MUohQjC8LQAA4mytKYmIOJ4gSTBELaFLEUMpH0oyn6smqHJ-gAIuiUFmhQ4pSsAT5yl4CpKviwFsb+NGlnM5b6i8XERtBopvkOJaqRW6CQFANCNtA5TdOekC1nWbYEB2XZDHeGnyQhSzuGum4wCEiCgK4MB2pYPxQFkTiqf4wjgFkaI6UMwBHqalk9h4Tg+EQ0DXhG07mgOVofmSKYOk6ik8f6yZbFlIbZdx8bKflQZFQpJWCuV0aplVSlRIm+WNmmNnZjlpVNfmqXvlELHfqBXKdbmzVAV+IHsdJjINblzXMSSCEvEhKFaS+mGkOCBh4XCCJSq4nAotO5G4moVFgTNVIojAjGRnBJIST+nL-mVfFDAJQlWCJirwMqE2SRqMnaoOFaQV1eVvdAlbsHxUDgClskg+l7pZS9bqZXslVg7mAafCWgb-rVGUFbG2MAS1qaar1Q5ozB7U2lTiNpdm1bGfWektvi2lMAjwPMzaxONuctO4yT4DnCGwtk2VwL4xgUtGvG+US4LHoK41MEoxcjN831BrS91vOWnr6nUxWrMmRzApc+0Rtyf1D3-U9f4KKE5SSJAwWWBrY2249Q20VglJux7XuK6NSYLUtK1oRhoKbdhkLQrtRFsvtRhUNdwXYqd+IIYHLz0c+mKwUyjusc7XKuyE7seMFiW5aKkMfbKX2ib94lOwHQPGzT1e157CXVX6TfinU3Q7k1BDgFuZkWWUPZ9vTLwAOowOuW7QAAzD2gogLY44N6Vt0vE4RIMNRQ+1h447hZAIQuDWzDezAd7ENeRBn-2TNFrD44iaoIIQwDLQHCNAEIkgJwbn4MuZw8pwDgHHHcfo0V5Q-SiGfNe9kEEThwZAu+2AKBhGbNsSAi55SAPiv4SQGR6amx-jTLSoUKFqFUE4D0dskYOy1o6Wa4NRatUqiNEetUhHDyJjw4qPtI4Y09D3e2BphHQWanQ8ug0pp8IjpkRBMBUJt3QfiOhOte6aW0uiIYHg6zAHYQ6Th-M6oOmFko9GYsVbAk0SI2WksPHKwcRcDxyiZFizambeSzi6ahIdv7DR4TfY5HGhXbuM1YmR3utHZCPRuL0njltHCO0CKwHcPAPi4DjBECOnKHOlF86knkVw-WPBvIwA8Aec8BBLwf3OjRWpM0pSqC0NAAAgpWAAkmiIgj4xRDBGWocpqI5QPmYN0W6c8eyPgvswchM0i63WgAAagYLgG4N0snWJ4FxPix1qHhT1HyX6UQ+TdDHDgII7Db4RW6gfEA7sjBHEXkM0Z4zHywKwXxfwFBOjjikHuA8Jh9zNgIEPCMThJy7PKOiJoDw7wEKMiZTCNSSR1P5gpMcTSexBUfu0q84wCXgSDn0vwJAAVjOopMnJidcLJwIoM+AtAQhHSoKUwQFSrBVLOrS5evIyUtMpR0ml1ESx0peAygZwyWXMEmXSa6cAykojoAAKQIOUUgsBdW0Hioa8oAAeAuAAxQYVATC4KbJAOsY5QA8H4MXQYGRTXCvNdAS1JY-VzINUaykyJUSOvgNIDIkMZnMG1XKaNsaTVmrDeUAu9AjnapWdzXRVg9xDB8DG4KAAfMtiJbBUHuZYIYIQCBZBALWTOoBbBpv9RmxVIa9UWvDegKQ3BtEPD0WgsSHbQ19utQXHZpyJ29sDUarNOaaRztBNeVQQhug9oDZaqZaE962BKb8QecoVAYoeAACiwNOWcdAXJIBAAASi6Yq5eHFSWVFfhStpcqWC0t6UA1VgLWXjFBNkIAA)

![Sequence diagram](https://user-images.githubusercontent.com/4972503/173007675-06da4771-3e51-4231-b1ae-4a1050c1c8ce.png)

**Comment by rovandep** [comment]
Updated based on Design meeting held on June 9th 2022 with @cvlc @mhmxs @vfiftyfive @rovandep 

- Multi KMS support only means one at a time (#5)
- Main space of Trousseau multi KMS is hybridish clouds, with Trousseau users have to have separate config only for Trousseau and not the entire KMS configuration per platform
- A migration helper would be nice, when user replaces KMS plugin, Trousseau should help migrating old secrets to new (#105)
- KMS plugins moves to separate sidecars (#103)
- KMS plugins provide a unix socket with a simple interface (#103)
- BYOKP: bring your own KMS plugin, users just mount any self implementation (#103)
- Once Vault moved to it's own sidecar, we should put main gRPC service into a sidecar:
  - There is an issue with unix sockets now. If Trousseau dies, but api server has a reference/bind mount to the old socket file, api server stops working. (#102)
  - So if we have an unbreakable simple process which creates unix socket, we can proxy requests to Trousseau. Why it is good? It makes product more robust (#104):
    - We have the same unix socket all the time, so crash won't break the entire cluster
    - We can try to reconnect before Kubernetes times out in the same connection
    - We can implement retry, failover, circuit breaker, whatever we want to find a ready instance as quick as possible
