### ISSUE TITLE
Kind doesn't work for local testing

### ISSUE THREAD

**Issue by mhmxs** [ondat/trousseau#56]
For local testing we use Kind to create a cluster, but there are some problems with the concept:

 - `config.yaml` is missing, so user has to create it manually
 - There is a chicken and an egg issue: api server is waiting for Trousseau unix socket, but Trousseau is not deploys without api server
 - I don't find any code snippet where Trousseau pod exposes the unix socket to the host
 - There are pod and daemonset based solutions but it isn't clear which one use and where
 - I think `/etc/kubernetes/manifests/kubernetes-kms.yaml` is not the right place for static pods, official docs mentions `/etc/kubelet.d`
 - e2e docs contains obsolete information

**Comment by rovandep** [comment]
@mhmxs is this issue still relevant?

**Comment by mhmxs** [comment]
@rovandep I'm following this guide: https://github.com/ondat/trousseau/blob/main/localdev.md and it works.

**Comment by rovandep** [comment]
Thanks! Closing the issues then.
